[package]
name = "src"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = {version = "0.4", features = ["canvas"]}
iced_aw = { version = "0.2", default-features = false, features = ["card"]}
num-traits = "0.2"
round = "0.1.2"

[[bin]]
name = "src"
path = "main.rs"
